apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels: 
    app: rabbitmq
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec: 
      containers:
        - name: rabbitmq
          image: 180377044868.dkr.ecr.us-east-1.amazonaws.com/rabbitmq:3
          ports:
            - containerPort: 15672