apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-deployment
  labels: 
    app: restaurante-api
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: restaurante-api
  template:
    metadata:
      labels:
        app: restaurante-api
    spec: 
      containers:
        - name: restaurante-api
          image: 180377044868.dkr.ecr.us-east-1.amazonaws.com/restauranteservice:1.5
          ports:
            - containerPort: 5101
          env:
            - name: ConnectionStrings__RestauranteConnection
              value: "server=microsvc-db.cs3ftz2dr3yx.us-east-1.rds.amazonaws.com;database=restaurantedb;user=admin;password=$mengo2023"
            - name: RabbitMqHost
              value: "rabbitmq-svc"
            - name: RabbitMqPort
              value: "5672"